image: node:lts
before_script:
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
stages:
  - deploy
deploy:
  stage: deploy
  script:
    - ssh deployer@"$SERVER" -p 2022 "cd /var/www/evlis && git reset --hard origin/master && git pull origin master"
    - ssh  deployer@"$SERVER" -p 2022 "cd /var/www/evlis && rm package-lock.json && npm install"
    - ssh deployer@"$SERVER" -p 2022 "cd /var/www/evlis && npm run build && rm -rf ../duonglt.net/* && cp dist/* ../duonglt.net/"
  only:
    - master
